# Generated by Django 3.2.6 on 2021-09-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('classes', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='ajax.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='to_teachers',
            field=models.ManyToManyField(db_column='teacher_id', to='ajax.Teachers'),
        ),
    ]
