# Generated by Django 3.2.6 on 2021-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210821_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_column='author_id', to='app01.Author'),
        ),
    ]
