# Generated by Django 3.2.6 on 2021-08-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAndAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.book')),
            ],
        ),
    ]
