# Generated by Django 3.2.6 on 2021-08-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_bookandauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookandauthor',
            name='book',
            field=models.ForeignKey(db_column='123', on_delete=django.db.models.deletion.CASCADE, to='app01.book'),
        ),
    ]
