# Generated by Django 3.2.6 on 2021-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='alex', max_length=32),
            preserve_default=False,
        ),
    ]
